apiVersion: v1
kind: Dns
metadata:
  name: example-dns
  namespace: default
spec:
  host: example-service
  paths:
    - subPath: /python
      serviceName: example-service
      servicePort: 4335
    - subPath: /asdf
      serviceName: example-service-2
      servicePort: 80