apiVersion: v1
kind: Job
metadata:
  name: job2
  namespace: default
spec:
  partition: dgx2
  nodes: 1
  ntasksPerNode: 6
  cpusPerTask: 1
  gres: gpu:1
file:
  /root/minik8s/pkg/jobserver/cuda_code/matrix_mul.cu
script: |
  nvcc -o matrix_mul matrix_mul.cu
  ./matrix_mul