apiVersion: v1
kind: Pod
metadata:
  name: pod-example
  labels:

spec:
  containers:
  - name: nginx
    image: nginx:stable-alpine
    ports:
    - containerPort: 80
  - name: redis
    image: redis:alpine
