apiVersion: v1
kind: Pod
metadata:
  name: pod-example
  labels:
    app: hpa-example
spec:
  containers:
  - name: nginx
    image: nginx:stable-alpine
    ports:
    - containerPort: 80
    resources:
      cpu: 0.1
      memory: 0.1
