apiVersion: v1
kind: Pod
metadata:
  name: pod-example
  labels:
    app: example-app
spec:
  containers:
  - name: nginx
    image: nginx:stable-alpine
    ports:
    - containerPort: 80

status:
  cpuUsage: 0.1
  memUsage: 0.1
