apiVersion: v1
kind: Pod
metadata:
  name: http-server-2
  labels:
    app: myapp-2
spec:
  containers:
    - name: http-server-2
      image: python:3.9-alpine
      command: []
      ports:
        - containerPort: 4335