apiVersion: v1
kind: Pod
metadata:
  name: http-server-3
  labels:
    svc: example-service-3
    app: hpa-example
spec:
  containers:
    - name: http-server-2
      image: python:3.9-alpine
      command: ["python", "-m", "http.server", "4335"]
      ports:
        - containerPort: 4335