apiVersion: v1
kind: Pod
metadata:
  name: pod-example
  labels:
    app: hpa-example
spec:
  containers:
  - name: nginx
    image: nginx:stable-alpine
    ports:
    - containerPort: 80
  - name: http-server
    image: python:3.9-alpine
    command: ["python", "-m", "http.server", "4335"]
    ports:
    - containerPort: 4335