apiVersion: v1
kind: Pod
metadata:
  name: pod-example
  labels:
    svc: example-service
spec:
  containers:
    - name: ubuntu1
      image: ubuntu:latest
      command: ["sleep", "infinity"]
      volumeMounts: 
        - name: mysql-storage
          mountPath: /data
    - name: ubuntu2
      image: ubuntu:latest
      command: ["sleep", "infinity"]
      volumeMounts: 
        - name: mysql-storage
          mountPath: /data
  volumes:
    - name: mysql-storage
      hostPath: 
        path: /data
     
