apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: default
spec:
  selector:
    app: myapp
  ports:
    - name: http
      protocol: TCP
      port: 4335
      targetPort: 4335
      nodePort: 30080
  type: NodePort
