apiVersion: v1
kind: Service
metadata:
  name: example-service-2
  namespace: default
spec:
  selector:
    svc: example-service-2
  ports:
    - name: http
      protocol: TCP
      port: 4335
      targetPort: 4335
      nodePort: 30080
  type: ClusterIP
