apiVersion: v1
kind: Service
metadata:
  name: example-service-2
  namespace: default
spec:
  selector:
    svc: hpa-example
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: ClusterIP
