apiVersion: v1
kind: Workflow
metadata:
  name: example-workflow
  namespace: default
spec:
  entryName: node1
  entryParam: {a: 1, b: 2}
  workflowNodes:
    - name: node1
      type: Function
      funcNode:
        funcNameSpace: default
        funcName: example-function
        nextNodeName: node2
        funcParam: ["a", "b"]
    - name: node2
      type: Choice
      choiceNode:
        expression: "$result > 10"
        trueNodeName: node3
        trueEntryParam: {a: $result, b: 1}
        falseNodeName: node1
        falseEntryParam: {a: $result, b: 2}
    - name: node3
      type: Function
      funcNode:
        funcNameSpace: default
        funcName: example-function
        nextNodeName: end
        funcParam: ["a", "b"]